/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.rustyrazorblade.code2snippets


import kotlin.test.Test
import kotlin.test.assertNotNull

class MainTest {
    @Test fun testAppHasAGreeting() {
        val m = Main()
    }
}
